services:
  django:
    build: ./backend
    container_name: backend
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend
    restart: always

  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:7
    networks:
      - backend
    restart: always

volumes:
  postgres_data:

networks:
  backend:
