# # GET  http://localhost:8000/api/activate/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.sU30l9m_tmqh_HzL9lvvy7nv7g-9Q18sxtRwMMslpQA
# # Content-Type: application/json
# # {}

GET  http://127.0.0.1:8000/api/user_info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NjAwNDU5LCJpYXQiOjE3MzU2MDAxNTksImp0aSI6Ijc2NGMzNDg1YTBmODQzMDVhNGY3ZjZkMmU4N2NmNzBhIiwidXNlcl9pZCI6Mn0.wk6B0ppb3bhh3cxzrgD9TyWjMs8IE2eYt3TQvIPcImY

{

}

#######

PUT  http://127.0.0.1:8000/api/update_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzEwOTA3LCJpYXQiOjE3MzQ3MTA2MDcsImp0aSI6ImQ2MmU4MGRiNDk4NzRhYWQ5ZGY2MGE4YjY5NzczZTBkIiwidXNlcl9pZCI6MX0.MEQx9K3zqd08-6Jpd25LAgEg5R0_RFNScnx4ILkvVx8

{
  # "email":"mio@gmail.com",
  "first_name":"89s"
}

##############
##############

POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Set-Cookie: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNTY5ODk1MCwiaWF0IjoxNzM1MDk0MTUwLCJqdGkiOiJhM2I2N2UyMzkyYjQ0NTMyODk0MDdjZTNiMWI5OGMyNCIsInVzZXJfaWQiOjN9.R4rsCbh8f3cQ1JUjsRz5iii0hH1HNl2dhyN-dfKRyVo; HttpOnly; Path=/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTg2NTI0LCJpYXQiOjE3MzU1ODYyMjQsImp0aSI6ImQyODYwNzUxNzg4YTQ3MTg4NzY3YmViNjdhNGZiYjk0IiwidXNlcl9pZCI6M30.r-GREqbbpMtnQfhK3c2jH72qrwuPxVNoQ-R6QQY3FDA

{
  "email": "testa@example.com",
  "password": "orllld123"
}

##############
##############

GET http://127.0.0.1:8000/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0Mzc5MzA2LCJpYXQiOjE3MzQzNzkwMDYsImp0aSI6IjBkMTZlYTNhMmZkNzRhZTQ4ZDAwNDM4YjkxNWE3NTE2IiwidXNlcl9pZCI6Mn0.euEQ98goSf4BFW0xxLtnYzJStS1CPyHW84enTqs-Y28

{
	"chat_id": 4
}

##############
##############


POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "email": "aoutifrak@example.com",
  "password": "orllld123"
}

##############
##############

POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{
  "username": "aoutifrak",
  "email": "aoutifrak@example.com",
  "password": "orllld123"
}

##############
##############

GET http://127.0.0.1:8000/api/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTg4MDI1LCJpYXQiOjE3MzU1ODc3MjUsImp0aSI6IjdiODkyN2RmMTMzYTRjZGRhMzlhMjJmZWRmMTYzYWU2IiwidXNlcl9pZCI6M30.93J3DYo6V6hVbykn-TQX7l-ddNg3RUdzUs822dbWTI0

{
  "username":"testa"
}
##################
##################

GET http://127.0.0.1:8000/api/friend_req/?type=received&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTg3NzA5LCJpYXQiOjE3MzU1ODc0MDksImp0aSI6Ijg5ZTVhNzEwMWRlYjRhOGE5YzQxNmFmMWMyMTM3NjRlIiwidXNlcl9pZCI6M30.a6iCLAgsfY8z_j8uNl2YSZPubEJg77N8tjNoqLgAU_c

{
  "username":"testa"
}

###########
###########
###########

PUT http://127.0.0.1:8000/api/friend_req/?type=received&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTc4NDA0LCJpYXQiOjE3MzU1NzgxMDQsImp0aSI6IjYyOWNiNzRjMGYyNTQwNzE5YzJkMzhhOWMyYzJhYTIyIiwidXNlcl9pZCI6Mn0.Ck7jU4jLDmbV68Ohl6ZNOq5Gw-9YbrE9oiUhMwjXJjM

{
  "username":"user1"
}

#########################

GET http://127.0.0.1:8000/api/notification/notif
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTc4NDA0LCJpYXQiOjE3MzU1NzgxMDQsImp0aSI6IjYyOWNiNzRjMGYyNTQwNzE5YzJkMzhhOWMyYzJhYTIyIiwidXNlcl9pZCI6Mn0.Ck7jU4jLDmbV68Ohl6ZNOq5Gw-9YbrE9oiUhMwjXJjM

{
  "username":"user1"
}

#############
#############
#############


POST http://127.0.0.1:8000/api/search_username
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkzMzI5LCJpYXQiOjE3MzU1OTMwMjksImp0aSI6IjFmMjQwNzNjMzRjNTQ4ZDU5Y2UxMzEzZDVlYzEzNTlmIiwidXNlcl9pZCI6NH0.-qmN4jjrk4hmBs__vUsUa1dZXqvL1htnknJPIE4gKmM

{
  "username":""
}

#################
#################
#################

POST http://127.0.0.1:8000/api/search_user?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkzNDUxLCJpYXQiOjE3MzU1OTMxNTEsImp0aSI6IjY0NzEwOTcxOGM0MTRjYjU4MjljNjk3Nzc3NDFiOThiIiwidXNlcl9pZCI6MX0.sRhv5X8fFQ-tHL1WLQqvD5cvpRNaH6vyjT1yIDllHqs

{

}

###############
POST http://127.0.0.1:8000/api/oauth
Content-Type: application/json

{
  "platform":"github"
}
###############

GET http://localhost:8000/api/socialauth/?platform=github&code=c716ff99f883caf70523
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTg4ODY2LCJpYXQiOjE3MzU1ODg1NjYsImp0aSI6ImExMjExNjJjNjgzYTRhZmNhNzU0NDUwYmQwYWQ5ZWJmIiwidXNlcl9pZCI6M30.tWlwhYa87uCjWTslLWTeLkhfBs5dhsWD98UNyrydh0I

{
  "platform":"github"
}