# Generated by Django 4.2.16 on 2024-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_alter_game_player1_alter_game_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='game',
            name='type_game',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
