# Generated by Django 4.2.16 on 2024-12-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_game_loser_game_type_game_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='ball_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='paddle_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='paddle_player2',
            field=models.IntegerField(default=0),
        ),
    ]
