# Generated by Django 4.2.16 on 2024-12-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_game_left_paddle_dir_game_right_paddle_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ballSpeedX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='ballSpeedY',
            field=models.IntegerField(default=0),
        ),
    ]
