# Generated by Django 4.2.16 on 2024-12-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_game_ballspeedx_game_ballspeedy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ballSpeedX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='game',
            name='ballSpeedY',
            field=models.FloatField(default=0.0),
        ),
    ]
