# Generated by Django 4.2.16 on 2024-12-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0011_alter_game_ballspeedx_alter_game_ballspeedy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
