# Generated by Django 4.2.16 on 2025-01-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_alter_game_loser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ballSpeedX',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ballSpeedY',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_x',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bol_player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bol_player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='left_paddle_dir',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle_player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle_player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='right_paddle_dir',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score_player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score_player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='type_game',
        ),
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.JSONField(default=True),
        ),
    ]
