# Generated by Django 4.2.16 on 2025-01-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0013_remove_game_ballspeedx_remove_game_ballspeedy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.JSONField(default=dict),
        ),
    ]
