# Generated by Django 4.2.16 on 2024-12-31 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_player1', models.IntegerField(default=0)),
                ('bol_player1', models.BooleanField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('bol_player2', models.BooleanField(default=0)),
                ('paddle_player1', models.IntegerField(default=0)),
                ('paddle_player2', models.IntegerField(default=0)),
                ('ball_x', models.IntegerField(default=0)),
                ('ball_y', models.IntegerField(default=0)),
                ('ballSpeedX', models.FloatField(default=0.0)),
                ('ballSpeedY', models.FloatField(default=0.0)),
                ('left_paddle_dir', models.IntegerField(default=0)),
                ('right_paddle_dir', models.IntegerField(default=0)),
                ('winner', models.CharField(default='Unknown', max_length=100)),
                ('loser', models.CharField(default='Unknown', max_length=100)),
                ('type_game', models.CharField(blank=True, max_length=25)),
                ('room', models.CharField(blank=True, max_length=25)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
