# Generated by Django 4.2.16 on 2024-12-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_game_ball_x_game_ball_y_game_paddle_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bol_player1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bol_player2',
            field=models.BooleanField(default=0),
        ),
    ]
