# Generated by Django 4.2.16 on 2024-12-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_game_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='left_paddle_dir',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='right_paddle_dir',
            field=models.IntegerField(default=0),
        ),
    ]
