# Generated by Django 4.2.16 on 2024-11-29 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=68, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
